In [1]:
import requests

url_endpoint = "https://jsonplaceholder.typicode.com/posts/1"

response = requests.get(url_endpoint)

print(response.status_code)
print(response.text)

200
{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}

In [2]:
import requests

url = "https://jsonplaceholder.typicode.com/posts"

payload = {
    "title": "Belajar Requests",
    "body": "Ini contoh POST request",
    "userId": 1
}

response = requests.post(url, json=payload)

print(response.status_code)
print(response.json())

201
{'title': 'Belajar Requests', 'body': 'Ini contoh POST request', 'userId': 1, 'id': 101}

In [3]:
import requests

params = {
    "userId": 1
}

response = requests.get(
    "https://jsonplaceholder.typicode.com/posts",
    params=params
)

print(response.url)  # lihat URL lengkapnya
print(response.json())

https://jsonplaceholder.typicode.com/posts?userId=1
[{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}, {'userId': 1, 'id': 2, 'title': 'qui est esse', 'body': 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla'}, {'userId': 1, 'id': 3, 'title': 'ea molestias quasi exercitationem repellat qui ipsa sit aut', 'body': 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut'}, {'userId': 1, 'id': 4, 'title': 'eum et est occaecati', 'body': 'ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit'}, {'userId': 1, 'id': 5, 'title': 'nesciunt quas odio', 'body': 'repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque'}, {'userId': 1, 'id': 6, 'title': 'dolorem eum magni eos aperiam quia', 'body': 'ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae'}, {'userId': 1, 'id': 7, 'title': 'magnam facilis autem', 'body': 'dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas'}, {'userId': 1, 'id': 8, 'title': 'dolorem dolore est ipsam', 'body': 'dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae'}, {'userId': 1, 'id': 9, 'title': 'nesciunt iure omnis dolorem tempora et accusantium', 'body': 'consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas'}, {'userId': 1, 'id': 10, 'title': 'optio molestias id quia eum', 'body': 'quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error'}]

In [ ]:
import requests
import pandas as pd

r = requests.get('https://api.github.com/users/ekaf-pro/repos',
                 params={
                     'sort' : 'updated'
                 })

print(r.status_code)

items = r.json()

type(items)

200

list

In [17]:
df = pd.DataFrame(items)
df

,id,node_id,name,full_name,private,owner,html_url,description,fork,url,...,is_template,web_commit_signoff_required,has_pull_requests,pull_request_creation_policy,topics,visibility,forks,open_issues,watchers,default_branch
0,1284476994,R_kgDOTI-QQg,Eksperimen_SML_Eka-Fajar-Kharisma,ekaf-pro/Eksperimen_SML_Eka-Fajar-Kharisma,False,"{'login': 'ekaf-pro', 'id': 258985863, 'node_i...",https://github.com/ekaf-pro/Eksperimen_SML_Eka...,None,False,https://api.github.com/repos/ekaf-pro/Eksperim...,...,False,False,True,all,[],public,0,0,0,main
1,1286144523,R_kgDOTKkCCw,Workflow-CI,ekaf-pro/Workflow-CI,False,"{'login': 'ekaf-pro', 'id': 258985863, 'node_i...",https://github.com/ekaf-pro/Workflow-CI,None,False,https://api.github.com/repos/ekaf-pro/Workflow-CI,...,False,False,True,all,[],public,0,0,0,main
2,1272311085,R_kgDOS9XtLQ,crypto_trading_signal_pipeline,ekaf-pro/crypto_trading_signal_pipeline,False,"{'login': 'ekaf-pro', 'id': 258985863, 'node_i...",https://github.com/ekaf-pro/crypto_trading_sig...,None,False,https://api.github.com/repos/ekaf-pro/crypto_t...,...,False,False,True,all,[],public,0,0,0,main
3,1255701819,R_kgDOSth9Ow,kafka,ekaf-pro/kafka,False,"{'login': 'ekaf-pro', 'id': 258985863, 'node_i...",https://github.com/ekaf-pro/kafka,None,False,https://api.github.com/repos/ekaf-pro/kafka,...,False,False,True,all,[],public,0,0,0,main
4,1255591121,R_kgDOStbM0Q,day43-production,ekaf-pro/day43-production,False,"{'login': 'ekaf-pro', 'id': 258985863, 'node_i...",https://github.com/ekaf-pro/day43-production,None,True,https://api.github.com/repos/ekaf-pro/day43-pr...,...,False,False,True,all,[],public,0,0,0,main
5,1247318234,R_kgDOSliQ2g,day_42_Bigdata_Spark_Hadoop-main,ekaf-pro/day_42_Bigdata_Spark_Hadoop-main,False,"{'login': 'ekaf-pro', 'id': 258985863, 'node_i...",https://github.com/ekaf-pro/day_42_Bigdata_Spa...,None,False,https://api.github.com/repos/ekaf-pro/day_42_B...,...,False,False,True,all,[],public,0,0,0,main
6,1228919370,R_kgDOST_SSg,day_8-13_pandas,ekaf-pro/day_8-13_pandas,False,"{'login': 'ekaf-pro', 'id': 258985863, 'node_i...",https://github.com/ekaf-pro/day_8-13_pandas,None,False,https://api.github.com/repos/ekaf-pro/day_8-13...,...,False,False,True,all,[],public,0,0,0,main
7,1234995190,R_kgDOSZyH9g,day_19-23,ekaf-pro/day_19-23,False,"{'login': 'ekaf-pro', 'id': 258985863, 'node_i...",https://github.com/ekaf-pro/day_19-23,None,False,https://api.github.com/repos/ekaf-pro/day_19-23,...,False,False,True,all,[],public,0,0,0,main
8,1230997145,R_kgDOSV-GmQ,day_14-18_SQL,ekaf-pro/day_14-18_SQL,False,"{'login': 'ekaf-pro', 'id': 258985863, 'node_i...",https://github.com/ekaf-pro/day_14-18_SQL,None,False,https://api.github.com/repos/ekaf-pro/day_14-1...,...,False,False,True,all,[],public,0,0,0,main
9,1228885604,R_kgDOST9OZA,day_5_tambahan-python_Pandas,ekaf-pro/day_5_tambahan-python_Pandas,False,"{'login': 'ekaf-pro', 'id': 258985863, 'node_i...",https://github.com/ekaf-pro/day_5_tambahan-pyt...,None,False,https://api.github.com/repos/ekaf-pro/day_5_ta...,...,False,False,True,all,[],public,0,0,0,main
10,1227811820,R_kgDOSS7r7A,day_3-6_Python,ekaf-pro/day_3-6_Python,False,"{'login': 'ekaf-pro', 'id': 258985863, 'node_i...",https://github.com/ekaf-pro/day_3-6_Python,None,False,https://api.github.com/repos/ekaf-pro/day_3-6_...,...,False,False,True,all,[],public,0,0,0,main

In [18]:
import pandas as pd
r = requests.get('https://api.github.com/search/repositories',
                 params={
                    'q':'stars:>100000',
                    'sort':'stars',
                    'order':'desc',
                    'per_page': 50}
)

print(r.status_code)
items = r.json()['items']
type(items)

200

list

In [19]:
cols = ['full_name', 'description','html_url','language',
       'stargazers_count','forks_count','open_issues_count',
       'created_at','pushed_at','license','topics']

In [20]:
import pandas as pd

df = pd.DataFrame(items)[cols]
df

,full_name,description,html_url,language,stargazers_count,forks_count,open_issues_count,created_at,pushed_at,license,topics
0,codecrafters-io/build-your-own-x,Master programming by recreating your favorite...,https://github.com/codecrafters-io/build-your-...,Markdown,554228,51949,679,2018-05-09T12:03:18Z,2026-07-14T19:25:58Z,None,"[awesome-list, free, programming, tutorial-cod..."
1,sindresorhus/awesome,😎 Awesome lists about all kinds of interesting...,https://github.com/sindresorhus/awesome,NaN,520739,37531,105,2014-07-11T13:42:37Z,2026-09-02T02:10:47Z,"{'key': 'cc0-1.0', 'name': 'Creative Commons Z...","[awesome, awesome-list, lists, resources, unic..."
2,public-apis/public-apis,A collective list of free APIs,https://github.com/public-apis/public-apis,Python,489931,54374,2210,2016-03-20T23:49:42Z,2026-10-17T17:36:01Z,"{'key': 'mit', 'name': 'MIT License', 'spdx_id...","[api, apis, dataset, development, free, list, ..."
3,freeCodeCamp/freeCodeCamp,freeCodeCamp.org's open-source codebase and cu...,https://github.com/freeCodeCamp/freeCodeCamp,TypeScript,457386,49592,176,2014-12-24T17:49:19Z,2026-10-18T01:46:51Z,"{'key': 'bsd-3-clause', 'name': 'BSD 3-Clause ...","[careers, certification, community, curriculum..."
4,EbookFoundation/free-programming-books,:books: Freely available programming books,https://github.com/EbookFoundation/free-progra...,Python,399417,66940,94,2013-10-11T06:50:37Z,2026-10-18T00:26:58Z,"{'key': 'cc-by-4.0', 'name': 'Creative Commons...","[books, education, hacktoberfest, list, resource]"
5,openclaw/openclaw,The AI that really does things. Any OS. Any Pl...,https://github.com/openclaw/openclaw,TypeScript,392339,82473,9402,2025-11-24T10:16:47Z,2026-10-18T12:26:04Z,"{'key': 'mit', 'name': 'MIT License', 'spdx_id...","[ai, assistant, crustacean, molty, openclaw, o..."
6,donnemartin/system-design-primer,Learn how to design large-scale systems. Prep ...,https://github.com/donnemartin/system-design-p...,Python,374606,58892,627,2017-02-26T16:15:28Z,2026-09-15T01:10:09Z,"{'key': 'other', 'name': 'Other', 'spdx_id': '...","[design, design-patterns, design-system, devel..."
7,nilbuild/developer-roadmap,"Interactive roadmaps, guides and other educati...",https://github.com/nilbuild/developer-roadmap,TypeScript,369739,45102,3,2017-03-15T13:45:52Z,2026-10-16T16:41:47Z,"{'key': 'other', 'name': 'Other', 'spdx_id': '...","[angular-roadmap, backend-roadmap, blockchain-..."
8,jwasham/coding-interview-university,A complete computer science study plan to beco...,https://github.com/jwasham/coding-interview-un...,NaN,362780,84952,129,2016-06-06T02:34:12Z,2025-08-28T14:42:47Z,"{'key': 'cc-by-sa-4.0', 'name': 'Creative Comm...","[algorithm, algorithms, coding-interview, codi..."
9,vinta/awesome-python,"The definitive list that answers ""I want to do...",https://github.com/vinta/awesome-python,Python,328335,28953,24,2014-06-27T21:00:06Z,2026-10-17T08:58:57Z,"{'key': 'other', 'name': 'Other', 'spdx_id': '...","[awesome, awesome-list, python, python-framewo..."
10,awesome-selfhosted/awesome-selfhosted,A list of Free Software network services and w...,https://github.com/awesome-selfhosted/awesome-...,NaN,327863,15398,0,2015-06-01T02:33:17Z,2026-10-18T10:48:41Z,"{'key': 'other', 'name': 'Other', 'spdx_id': '...","[awesome, awesome-list, cloud, free-software, ..."
11,morluto/rea,"Reverse engineer anything with agents, from ap...",https://github.com/morluto/rea,TypeScript,315415,79961,1214,2026-04-14T00:51:32Z,2026-10-18T12:30:16Z,"{'key': 'mit', 'name': 'MIT License', 'spdx_id...","[agent-skills, ai-agents, binary-analysis, cla..."
12,obra/superpowers,An agentic skills framework & software develop...,https://github.com/obra/superpowers,Shell,301431,26913,378,2025-10-09T19:45:18Z,2026-10-10T03:03:30Z,"{'key': 'mit', 'name': 'MIT License', 'spdx_id...","[ai, brainstorming, coding, obra, sdlc, skills..."
13,mattpocock/skills,Skills for Real Engineers. Straight from my .a...,https://github.com/mattpocock/skills,Shell,295666,24807,190,2026-02-03T11:15:53Z,2026-10-13T08:46:40Z,"{'key': 'mit', 'name': 'MIT License', 'spdx_id...",[]
14,practical-tutorials/project-based-learning,Curated list of project-based tutorials,https://github.com/practical-tutorials/project...,Python,287122,36632,236,2017-04-12T05:07:46Z,2026-10-12T07:22:00Z,"{'key': 'mit', 'name': 'MIT License', 'spdx_id...","[beginner-project, cpp, golang, javascript, pr..."
15,affaan-m/ECC,The agent harness performance optimization sys...,https://github.com/affaan-m/ECC,JavaScript,282961,42021,240,2026-01-18T00:51:51Z,2026-10-15T19:17:01Z,"{'key': 'mit', 'name': 'MIT License', 'spdx_id...","[ai-agents, anthropic, claude, claude-code, de..."
16,996icu/996.ICU,Repo for counting stars and contributing. Pres...,https://github.com/996icu/996.ICU,NaN,277156,20682,16689,2019-03-26T07:31:14Z,2025-08-22T06:01:29Z,"{'key': 'other', 'name': 'Other', 'spdx_id': '...",[]
17,NousResearch/hermes-agent,The agent that grows with you,https://github.com/NousResearch/hermes-agent,Python,254818,55411,49918,2025-07-22T22:22:28Z,2026-10-18T12:26:35Z,"{'key': 'mit', 'name': 'MIT License', 'spdx_id...","[ai, ai-agent, ai-agents, anthropic, chatgpt, ..."
18,deepseek-ai/deepseek-harness,DeepSeek Harness: Everything is a Plugin.,https://github.com/deepseek-ai/deepseek-harness,TypeScript,252752,30404,0,2026-08-13T11:56:32Z,2026-10-17T08:16:09Z,"{'key': 'mit', 'name': 'MIT License', 'spdx_id...","[ai-agents, cordis, dsh, dsh-plugin]"
19,torvalds/linux,Linux kernel source tree,https://github.com/torvalds/linux,C,252352,68263,3,2011-09-04T22:48:12Z,2026-10-18T05:12:42Z,"{'key': 'other', 'name': 'Other', 'spdx_id': '...",[]
20,react/react,The library for web and native user interfaces.,https://github.com/react/react,JavaScript,251253,51527,1460,2013-05-24T16:15:54Z,2026-10-15T08:14:36Z,"{'key': 'mit', 'name': 'MIT License', 'spdx_id...","[declarative, frontend, javascript, library, r..."
21,trimstray/the-book-of-secret-knowledge,"A collection of inspiring lists, manuals, chea...",https://github.com/trimstray/the-book-of-secre...,NaN,251068,14553,175,2018-06-23T10:43:14Z,2024-11-19T14:00:38Z,"{'key': 'mit', 'name': 'MIT License', 'spdx_id...","[awesome, awesome-list, bsd, cheatsheets, devo..."
22,TheAlgorithms/Python,All Algorithms implemented in Python,https://github.com/TheAlgorithms/Python,Python,225367,51184,35,2016-07-16T09:44:01Z,2026-10-16T20:23:44Z,"{'key': 'mit', 'name': 'MIT License', 'spdx_id...","[algorithm, algorithm-competitions, algorithms..."
23,multica-ai/andrej-karpathy-skills,A single CLAUDE.md file to improve Claude Code...,https://github.com/multica-ai/andrej-karpathy-...,NaN,220826,22176,134,2026-01-27T03:53:13Z,2026-04-20T10:05:04Z,None,[]
24,anomalyco/opencode,The open source coding agent.,https://github.com/anomalyco/opencode,TypeScript,215960,28924,4660,2025-04-30T20:08:00Z,2026-10-18T12:20:56Z,"{'key': 'mit', 'name': 'MIT License', 'spdx_id...",[]
25,vuejs/vue,"This is the repo for Vue 2. For Vue 3, go to h...",https://github.com/vuejs/vue,TypeScript,212622,33675,639,2013-07-29T03:24:51Z,2024-10-10T07:24:15Z,"{'key': 'mit', 'name': 'MIT License', 'spdx_id...","[framework, frontend, javascript, vue]"
26,ossu/computer-science,🎓 Path to a free self-taught education in Comp...,https://github.com/ossu/computer-science,HTML,210098,26007,29,2014-05-04T00:18:39Z,2026-07-14T05:38:25Z,"{'key': 'mit', 'name': 'MIT License', 'spdx_id...","[awesome-list, computer-science, courses, curr..."
27,n8n-io/n8n,Fair-code workflow automation platform with na...,https://github.com/n8n-io/n8n,TypeScript,207881,61172,1193,2019-06-22T09:24:21Z,2026-10-18T11:37:30Z,"{'key': 'other', 'name': 'Other', 'spdx_id': '...","[ai, apis, automation, cli, data-flow, develop..."
28,DigitalPlatDev/FreeDomain,Free domain registration and practical DNS lea...,https://github.com/DigitalPlatDev/FreeDomain,Markdown,204739,4531,38,2024-05-30T13:23:00Z,2026-08-12T10:36:46Z,"{'key': 'agpl-3.0', 'name': 'GNU Affero Genera...","[digitalplat, dns, dns-tutorial, documentation..."
29,tensorflow/tensorflow,An Open Source Machine Learning Framework for ...,https://github.com/tensorflow/tensorflow,C++,201083,79701,3403,2015-11-07T01:19:20Z,2026-10-18T10:57:48Z,"{'key': 'apache-2.0', 'name': 'Apache License ...","[deep-learning, deep-neural-networks, distribu..."
30,yt-dlp/yt-dlp,A feature-rich command-line audio/video downlo...,https://github.com/yt-dlp/yt-dlp,Python,199067,17377,2716,2020-10-26T04:22:55Z,2026-10-10T21:15:52Z,"{'key': 'unlicense', 'name': 'The Unlicense', ...","[cli, downloader, python, sponsorblock, youtub..."
31,trekhleb/javascript-algorithms,📝 Algorithms and data structures implemented i...,https://github.com/trekhleb/javascript-algorithms,JavaScript,196680,31002,414,2018-03-24T07:47:04Z,2026-07-26T02:43:08Z,"{'key': 'mit', 'name': 'MIT License', 'spdx_id...","[algorithm, algorithms, computer-science, data..."
32,ultraworkers/claw-code,"An agent-managed museum exhibit, built in Rust...",https://github.com/ultraworkers/claw-code,Rust,194915,107920,9,2026-03-31T08:58:08Z,2026-10-13T08:57:11Z,"{'key': 'mit', 'name': 'MIT License', 'spdx_id...",[]
33,massgravel/Microsoft-Activation-Scripts,Open-source Windows and Office activator featu...,https://github.com/massgravel/Microsoft-Activa...,Batchfile,194905,18480,3,2020-01-12T23:03:34Z,2026-10-17T01:33:16Z,"{'key': 'gpl-3.0', 'name': 'GNU General Public...","[activator, hwid, kms, kms38, massgrave, massg..."
34,microsoft/vscode,Visual Studio Code,https://github.com/microsoft/vscode,TypeScript,193807,45796,21878,2015-09-03T20:23:38Z,2026-10-18T11:58:36Z,"{'key': 'mit', 'name': 'MIT License', 'spdx_id...","[editor, electron, microsoft, typescript, visu..."
35,firecrawl/firecrawl,Supercharge your AI agents with data from the ...,https://github.com/firecrawl/firecrawl,TypeScript,192634,10174,621,2024-04-15T21:02:29Z,2026-10-18T09:50:14Z,"{'key': 'agpl-3.0', 'name': 'GNU Affero Genera...","[ai, ai-agents, ai-crawler, ai-scraping, ai-se..."
36,microsoft/markitdown,Python tool for converting files and office do...,https://github.com/microsoft/markitdown,Python,190838,14195,737,2024-11-13T19:56:40Z,2026-10-04T03:59:52Z,"{'key': 'mit', 'name': 'MIT License', 'spdx_id...","[autogen, autogen-extension, langchain, markdo..."
37,ohmyzsh/ohmyzsh,"🙃 A delightful community-driven (with 2,500+...",https://github.com/ohmyzsh/ohmyzsh,Shell,190066,29635,298,2009-08-28T18:15:37Z,2026-10-13T09:22:27Z,"{'key': 'mit', 'name': 'MIT License', 'spdx_id...","[cli, cli-app, oh-my-zsh, oh-my-zsh-plugin, oh..."
38,avelino/awesome-go,"A curated list of awesome Go frameworks, libra...",https://github.com/avelino/awesome-go,Go,189028,13632,80,2014-07-06T13:42:15Z,2026-10-15T14:03:07Z,"{'key': 'mit', 'name': 'MIT License', 'spdx_id...","[awesome, awesome-list, go, golang, golang-lib..."
39,Significant-Gravitas/AutoGPT,AutoGPT is the vision of accessible AI for eve...,https://github.com/Significant-Gravitas/AutoGPT,Python,187637,45914,720,2023-03-16T09:21:07Z,2026-10-18T12:24:19Z,"{'key': 'other', 'name': 'Other', 'spdx_id': '...","[agentic-ai, agents, ai, artificial-intelligen..."
40,jackfrued/Python-100-Days,Python - 100天从新手到大师,https://github.com/jackfrued/Python-100-Days,Jupyter Notebook,187269,55759,718,2018-03-01T16:05:52Z,2026-07-29T15:18:29Z,None,[]
41,CyC2018/CS-Notes,:books: 技术面试必备基础知识、Leetcode、计算机操作系统、计算机网络、系统设计,https://github.com/CyC2018/CS-Notes,NaN,186269,50682,198,2018-02-13T14:56:24Z,2024-08-21T09:40:10Z,None,"[algorithm, computer-science, cpp, interview, ..."
42,getify/You-Dont-Know-JS,A book series (2 published editions) on the JS...,https://github.com/getify/You-Dont-Know-JS,NaN,184821,33358,2,2013-11-16T02:37:24Z,2026-02-15T04:36:44Z,"{'key': 'other', 'name': 'Other', 'spdx_id': '...","[async, book, book-series, closures, education..."
43,ollama/ollama,"Get up and running with Kimi, GLM, MiniMax, De...",https://github.com/ollama/ollama,Go,183695,18375,4331,2023-06-26T19:39:32Z,2026-10-18T06:06:02Z,"{'key': 'mit', 'name': 'MIT License', 'spdx_id...","[deepseek, gemma, gemma3, glm, go, golang, gpt..."
44,521xueweihan/HelloGitHub,:octocat: 分享 GitHub 上有趣、入门级的开源项目。Share interes...,https://github.com/521xueweihan/HelloGitHub,Python,182843,13027,1041,2016-05-04T06:24:11Z,2026-09-28T00:11:38Z,None,"[awesome, github, hellogithub, python]"
45,anthropics/skills,Public repository for Agent Skills,https://github.com/anthropics/skills,Python,181892,21538,1426,2025-09-22T15:53:31Z,2026-10-09T18:45:52Z,None,[agent-skills]
46,flutter/flutter,Flutter makes it easy and fast to build beauti...,https://github.com/flutter/flutter,Dart,180262,34342,13370,2015-03-06T22:54:58Z,2026-10-18T09:54:46Z,"{'key': 'bsd-3-clause', 'name': 'BSD 3-Clause ...","[android, app-framework, cross-platform, dart,..."
47,github/gitignore,A collection of useful .gitignore templates,https://github.com/github/gitignore,NaN,175979,82101,70,2010-11-08T20:17:14Z,2026-10-02T20:59:38Z,"{'key': 'cc0-1.0', 'name': 'Creative Commons Z...","[git, gitignore]"
48,twbs/bootstrap,"The most popular HTML, CSS, and JavaScript fra...",https://github.com/twbs/bootstrap,MDX,174927,78540,254,2011-07-29T21:19:00Z,2026-10-17T09:05:45Z,"{'key': 'mit', 'name': 'MIT License', 'spdx_id...","[bootstrap, css, css-framework, html, javascri..."
49,f/prompts.chat,"f.k.a. Awesome ChatGPT Prompts. Share, discove...",https://github.com/f/prompts.chat,HTML,173308,22165,89,2022-12-05T13:54:13Z,2026-10-18T03:17:54Z,"{'key': 'other', 'name': 'Other', 'spdx_id': '...","[ai, artificial-intelligence, awesome-list, ch..."