In [3]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import logging 
import time 

logging.basicConfig(
    level = logging.INFO,
    format= '%(asctime)s | %(name)s | %(levelname)s | %(message)s',
    handlers=[
        logging.FileHandler('scraping_uhuy.log', encoding='utf-8'), # ke file
        logging.StreamHandler()                                     # ke layar notebook
    ]
)

logger = logging.getLogger('book_scraper')
base_url = 'https://books.toscrape.com'

summary = []

for page in range(1,51):
    if page == 1 :
        url = base_url
    else :
        url = f'https://books.toscrape.com/catalogue/page-{page}.html'

    #pakai try except supaya tidak berhenti jika ada satu halaman yg gagal
    try :
        response = requests.get(url, timeout=10)
        response.raise_for_status()
    except requests.RequestException as e :
        logger.error(f'Halaman {page} gagal : {e}') #bedanya kalo pakai logging maka akan muncul 'Root' bukan nama loggernya
        continue 

    soup = BeautifulSoup(response.text, 'html.parser')
    books = soup.find_all('article', class_='product_pod')

    for book in books :
        title = book.h3.a.get('title')
        rating = book.find('p', class_='star-rating')['class'][1]
        harga = book.find('p', class_='price_color').get_text(strip=True)
        stok = book.find('p', class_='instock availability').get_text(strip=True)

        img_relatif = book.find('img')['src']
        img_url = urljoin(url,img_relatif)
        summary.append({
            'Title' : title,
            'Rating' : rating,
            'Price' : harga,
            'Stok' : stok,
            'Link Image' : img_url
        })
    logger.info(f'Selesai halaman {page}. Total {len(summary)} buku')
    time.sleep(0.5) #jeda sopan ke server

logger.info(f'Semua buku telah di Scraping. Total : {len(summary)}')

2026-10-21 06:30:52,525 | book_scraper | INFO | Selesai halaman 1. Total 20 buku
2026-10-21 06:30:54,769 | book_scraper | INFO | Selesai halaman 2. Total 40 buku
2026-10-21 06:30:56,916 | book_scraper | INFO | Selesai halaman 3. Total 60 buku
2026-10-21 06:30:59,069 | book_scraper | INFO | Selesai halaman 4. Total 80 buku
2026-10-21 06:31:01,263 | book_scraper | INFO | Selesai halaman 5. Total 100 buku
2026-10-21 06:31:03,473 | book_scraper | INFO | Selesai halaman 6. Total 120 buku
2026-10-21 06:31:05,621 | book_scraper | INFO | Selesai halaman 7. Total 140 buku
2026-10-21 06:31:07,868 | book_scraper | INFO | Selesai halaman 8. Total 160 buku
2026-10-21 06:31:10,004 | book_scraper | INFO | Selesai halaman 9. Total 180 buku
2026-10-21 06:31:12,170 | book_scraper | INFO | Selesai halaman 10. Total 200 buku
2026-10-21 06:31:14,317 | book_scraper | INFO | Selesai halaman 11. Total 220 buku
2026-10-21 06:31:16,472 | book_scraper | INFO | Selesai halaman 12. Total 240 buku
2026-10-21 06:31:18,623 | book_scraper | INFO | Selesai halaman 13. Total 260 buku
2026-10-21 06:31:20,873 | book_scraper | INFO | Selesai halaman 14. Total 280 buku
2026-10-21 06:31:23,074 | book_scraper | INFO | Selesai halaman 15. Total 300 buku
2026-10-21 06:31:25,280 | book_scraper | INFO | Selesai halaman 16. Total 320 buku
2026-10-21 06:31:27,433 | book_scraper | INFO | Selesai halaman 17. Total 340 buku
2026-10-21 06:31:29,602 | book_scraper | INFO | Selesai halaman 18. Total 360 buku
2026-10-21 06:31:31,734 | book_scraper | INFO | Selesai halaman 19. Total 380 buku
2026-10-21 06:31:33,880 | book_scraper | INFO | Selesai halaman 20. Total 400 buku
2026-10-21 06:31:36,027 | book_scraper | INFO | Selesai halaman 21. Total 420 buku
2026-10-21 06:31:38,193 | book_scraper | INFO | Selesai halaman 22. Total 440 buku
2026-10-21 06:31:40,343 | book_scraper | INFO | Selesai halaman 23. Total 460 buku
2026-10-21 06:31:42,549 | book_scraper | INFO | Selesai halaman 24. Total 480 buku
2026-10-21 06:31:44,971 | book_scraper | INFO | Selesai halaman 25. Total 500 buku
2026-10-21 06:31:47,110 | book_scraper | INFO | Selesai halaman 26. Total 520 buku
2026-10-21 06:31:49,186 | book_scraper | INFO | Selesai halaman 27. Total 540 buku
2026-10-21 06:31:51,309 | book_scraper | INFO | Selesai halaman 28. Total 560 buku
2026-10-21 06:31:53,438 | book_scraper | INFO | Selesai halaman 29. Total 580 buku
2026-10-21 06:31:55,598 | book_scraper | INFO | Selesai halaman 30. Total 600 buku
2026-10-21 06:31:57,690 | book_scraper | INFO | Selesai halaman 31. Total 620 buku
2026-10-21 06:31:59,810 | book_scraper | INFO | Selesai halaman 32. Total 640 buku
2026-10-21 06:32:02,082 | book_scraper | INFO | Selesai halaman 33. Total 660 buku
2026-10-21 06:32:04,208 | book_scraper | INFO | Selesai halaman 34. Total 680 buku
2026-10-21 06:32:06,311 | book_scraper | INFO | Selesai halaman 35. Total 700 buku
2026-10-21 06:32:08,577 | book_scraper | INFO | Selesai halaman 36. Total 720 buku
2026-10-21 06:32:10,654 | book_scraper | INFO | Selesai halaman 37. Total 740 buku
2026-10-21 06:32:12,790 | book_scraper | INFO | Selesai halaman 38. Total 760 buku
2026-10-21 06:32:14,931 | book_scraper | INFO | Selesai halaman 39. Total 780 buku
2026-10-21 06:32:16,994 | book_scraper | INFO | Selesai halaman 40. Total 800 buku
2026-10-21 06:32:19,134 | book_scraper | INFO | Selesai halaman 41. Total 820 buku
2026-10-21 06:32:21,286 | book_scraper | INFO | Selesai halaman 42. Total 840 buku
2026-10-21 06:32:23,439 | book_scraper | INFO | Selesai halaman 43. Total 860 buku
2026-10-21 06:32:25,603 | book_scraper | INFO | Selesai halaman 44. Total 880 buku
2026-10-21 06:32:27,786 | book_scraper | INFO | Selesai halaman 45. Total 900 buku
2026-10-21 06:32:30,010 | book_scraper | INFO | Selesai halaman 46. Total 920 buku
2026-10-21 06:32:32,142 | book_scraper | INFO | Selesai halaman 47. Total 940 buku
2026-10-21 06:32:34,293 | book_scraper | INFO | Selesai halaman 48. Total 960 buku
2026-10-21 06:32:36,405 | book_scraper | INFO | Selesai halaman 49. Total 980 buku
2026-10-21 06:32:38,484 | book_scraper | INFO | Selesai halaman 50. Total 1000 buku
2026-10-21 06:32:38,985 | book_scraper | INFO | Semua buku telah di Scraping. Total : 1000

In [2]:
df = pd.DataFrame(summary)

In [20]:
# Cek Sampling Link Image
df[df['Title'] == 'Soumission']['Link Image'].iloc()[0] #pakai .iloc()[0] agar hasilnya tidak terpotong

'https://books.toscrape.com/media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg'

In [21]:
df

,Title,Rating,Price,Stok,Link Image
0,A Light in the Attic,Three,Â£51.77,In stock,https://books.toscrape.com/media/cache/2c/da/2...
1,Tipping the Velvet,One,Â£53.74,In stock,https://books.toscrape.com/media/cache/26/0c/2...
2,Soumission,One,Â£50.10,In stock,https://books.toscrape.com/media/cache/3e/ef/3...
3,Sharp Objects,Four,Â£47.82,In stock,https://books.toscrape.com/media/cache/32/51/3...
4,Sapiens: A Brief History of Humankind,Five,Â£54.23,In stock,https://books.toscrape.com/media/cache/be/a5/b...
...,...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,One,Â£55.53,In stock,https://books.toscrape.com/media/cache/96/ee/9...
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",Four,Â£57.06,In stock,https://books.toscrape.com/media/cache/09/7c/0...
997,A Spy's Devotion (The Regency Spies of London #1),Five,Â£16.97,In stock,https://books.toscrape.com/media/cache/1b/5f/1...
998,1st to Die (Women's Murder Club #1),One,Â£53.98,In stock,https://books.toscrape.com/media/cache/2b/41/2...
999,"1,000 Places to See Before You Die",Five,Â£26.08,In stock,https://books.toscrape.com/media/cache/d7/0f/d...

In [23]:
df['Price'] = df['Price'].str.replace('Â','')

In [24]:
df

,Title,Rating,Price,Stok,Link Image
0,A Light in the Attic,Three,£51.77,In stock,https://books.toscrape.com/media/cache/2c/da/2...
1,Tipping the Velvet,One,£53.74,In stock,https://books.toscrape.com/media/cache/26/0c/2...
2,Soumission,One,£50.10,In stock,https://books.toscrape.com/media/cache/3e/ef/3...
3,Sharp Objects,Four,£47.82,In stock,https://books.toscrape.com/media/cache/32/51/3...
4,Sapiens: A Brief History of Humankind,Five,£54.23,In stock,https://books.toscrape.com/media/cache/be/a5/b...
...,...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,One,£55.53,In stock,https://books.toscrape.com/media/cache/96/ee/9...
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",Four,£57.06,In stock,https://books.toscrape.com/media/cache/09/7c/0...
997,A Spy's Devotion (The Regency Spies of London #1),Five,£16.97,In stock,https://books.toscrape.com/media/cache/1b/5f/1...
998,1st to Die (Women's Murder Club #1),One,£53.98,In stock,https://books.toscrape.com/media/cache/2b/41/2...
999,"1,000 Places to See Before You Die",Five,£26.08,In stock,https://books.toscrape.com/media/cache/d7/0f/d...